import Header from "@/components/header"
import Footer from "@/components/footer"
import { getServerSession } from "next-auth"
import { authOptions } from "@/app/api/auth/[...nextauth]/route"
import "../styles/globals.css"
import Link from "next/link"

export const metadata = {
  title: "Dashboard demographie",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang='fr'>
      <body className='flex flex-col bg-gradient-to-b from-gray-100 to-gray-300 m-auto w-1/1 p-4 px-4 max-w-screen-xl'>
        <h1 className='text-teal-500 font-bold text-center mb-5 text-2xl italic'>
          <Link href='/'>Démographie Mondiale</Link>
        </h1>
        <Header session={session} />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
