import "./globals.css"

export const metadata = {
  title: "Dashboard demographie",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='fr'>
      <body>{children}</body>
    </html>
  )
}
